apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: ClusterIP
  selector:
    app: helloworld
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-external
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
  - name: http
    port: 80
    targetPort: 80